language: cpp
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq cmake libssl-dev libprotobuf-dev protobuf-compiler liblzma-dev zlib1g-dev liblzo2-dev"
install: true
script: mkdir objdir && cd objdir && cmake ../ && make
