.TH zbackup 5
.SH NAME
zbackup \- versatile deduplicating backup tool
.SH DESCRIPTION
This manual page describes on how to generate the password file.
.SH STEPS
First, run
.B echo mypassword > ~/.my_backup_password
in a terminal. Then run
.B chmod 600 ~/.my_backup_password
to set correct permissions. See
.BR chmod (1)
for details.
.SH ENVIRONMENTS
.B mypassword
Your password that you want to use for encrpying the backup repository and encrpyt/decrpyting the backup files.
.SH AUTHOR
Howard Chan <smartboyhw AT gmail DOT com>
.SH "SEE ALSO"
.B chmod (1)
